name: Deploy Sphinx documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # using Python 3.12 to match venv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv312
          source venv312/bin/activate
          pip install sphinx sphinx_rtd_theme myst-nb numpy scipy matplotlib numba joblib

      - name: Prepare documentation files
        run: |
          cp examples/tutorial.ipynb docs/userdocs/tutorial.ipynb
          cp CHANGELOG.md docs/devdocs/changelog.md
          cp CODE_OF_CONDUCT.md docs/devdocs/code_of_conduct.md
          cp CONTRIBUTING.md docs/devdocs/contributing.md

      - name: Generate API documentation
        run: |
          source venv312/bin/activate
          sphinx-apidoc -f -o docs/apidocs src/crisprzip --separate

      - name: Build documentation
        run: |
          source venv312/bin/activate
          rm -rf docs/_build docs/jupyter_execute
          sphinx-build docs docs/_build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
          force_orphan: true
